Final features
Haywayaheadshot/to-do-list-with-webpack-es6 pull request #3
Opened 2022-10-06 22:40 UTC by Haywayaheadshot

### What?

I created the structure for a to-do list that helps people manage their activities.

### Why?

This is to help them manage their activities and also help them plan their days easily.

### How?
> I installed webpack and made all the necessary configurations to ensure a good front-end environment.
> Created the structure of the page in my index.html file which can be found in the source folder.
> I then imported styles.css to index.js and then used it to style the HTML file.
> I added an edit button where the user can edit tasks.
> I added a checkbox input to allow the user tick out the finished task.
> When the checkbox is checked, a line runs through the task to signify it has been cancelled.
> The "Clear all activities" button at the bottom of the app, clears all completed tasks.
> I dynamically created the ul where the task will be added.
> I created a class constructor to handle task inputs from user and hence created a newTask.
> I made sure to use modules in my structure so I imported and exported variables and functions between index.js, Variables.js, Constructor.js, and Functions.js
> I added all input information to local storage.
> Also when the data is deleted on the UI, it gets deleted in local storage too.
> I created a function to retrieve data stored in the local storage and display them once the user loads the app
> I styled the desktop version of the app

2022-10-06 23:17 UTC, rloterh requested changes
Hi Abubakar, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- Tasks are saved to local storage correctly
- Local storage updates correctly on users' action


## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**You can also consider:**
- I think you should change the header title _Authors_ to _Author_ in your ReadMe, as this project is worked on by a sole contributor. 
- I think you should replace the sub heading text Author1 with your full name in your ReadMe.
Implementing the above change(s) will make your ReadMe appear more professional.
<br>
Cheers and Happy coding!👏 💻 🍷
<br><br>
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-06 23:17 UTC, rloterh commented on src/index.js
>  });
- [ ] This activity requires that you use `Array.filter()` method alongside with the _Clear all completed_ button in removing all completed tasks, which is not implemented in your project. Kindly ensure to improve upon the same.

2022-10-06 23:21 UTC, Haywayaheadshot commented on src/index.js
>  });
@rloterh Thank you for reviewing my project. I will work on the changes asap

2022-10-07 04:05 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @Haywayaheadshot, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 04:10 UTC, Haywayaheadshot commented
@Mihndim2020 Thank you so much for reviewing my code. Have a great weekend.

2022-10-07 04:10 UTC, merged